/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Contest {
  'id' : bigint,
  'participants' : Array<Principal>,
  'name' : string,
  'entryFee' : bigint,
  'prizePool' : bigint,
}
export interface FantasyTeam {
  'id' : bigint,
  'playerIds' : Array<bigint>,
  'owner' : Principal,
}
export interface Player {
  'id' : bigint,
  'form' : bigint,
  'name' : string,
  'team' : string,
  'price' : bigint,
  'position' : string,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile { 'balance' : bigint, 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addPlayer' : ActorMethod<[Player], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'awardPrize' : ActorMethod<[Principal, bigint], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createContest' : ActorMethod<[string, bigint, bigint], bigint>,
  'createTeam' : ActorMethod<[Array<bigint>], bigint>,
  'depositFunds' : ActorMethod<[bigint], undefined>,
  'getAllContests' : ActorMethod<[], Array<Contest>>,
  'getAllPlayers' : ActorMethod<[], Array<Player>>,
  'getBalance' : ActorMethod<[], bigint>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContest' : ActorMethod<[bigint], [] | [Contest]>,
  'getMyTeams' : ActorMethod<[], Array<FantasyTeam>>,
  'getPlayer' : ActorMethod<[bigint], [] | [Player]>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getTeam' : ActorMethod<[bigint], [] | [FantasyTeam]>,
  'getUser' : ActorMethod<[], UserProfile>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'joinContest' : ActorMethod<[bigint], undefined>,
  'registerUser' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updatePlayer' : ActorMethod<[bigint, Player], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];