/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Player = IDL.Record({
  'id' : IDL.Nat,
  'form' : IDL.Nat,
  'name' : IDL.Text,
  'team' : IDL.Text,
  'price' : IDL.Nat,
  'position' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const Contest = IDL.Record({
  'id' : IDL.Nat,
  'participants' : IDL.Vec(IDL.Principal),
  'name' : IDL.Text,
  'entryFee' : IDL.Nat,
  'prizePool' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'balance' : IDL.Nat,
  'name' : IDL.Text,
});
export const FantasyTeam = IDL.Record({
  'id' : IDL.Nat,
  'playerIds' : IDL.Vec(IDL.Nat),
  'owner' : IDL.Principal,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addPlayer' : IDL.Func([Player], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'awardPrize' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createContest' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [IDL.Nat], []),
  'createTeam' : IDL.Func([IDL.Vec(IDL.Nat)], [IDL.Nat], []),
  'depositFunds' : IDL.Func([IDL.Nat], [], []),
  'getAllContests' : IDL.Func([], [IDL.Vec(Contest)], ['query']),
  'getAllPlayers' : IDL.Func([], [IDL.Vec(Player)], ['query']),
  'getBalance' : IDL.Func([], [IDL.Nat], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContest' : IDL.Func([IDL.Nat], [IDL.Opt(Contest)], ['query']),
  'getMyTeams' : IDL.Func([], [IDL.Vec(FantasyTeam)], ['query']),
  'getPlayer' : IDL.Func([IDL.Nat], [IDL.Opt(Player)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getTeam' : IDL.Func([IDL.Nat], [IDL.Opt(FantasyTeam)], ['query']),
  'getUser' : IDL.Func([], [UserProfile], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'joinContest' : IDL.Func([IDL.Nat], [], []),
  'registerUser' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updatePlayer' : IDL.Func([IDL.Nat, Player], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Player = IDL.Record({
    'id' : IDL.Nat,
    'form' : IDL.Nat,
    'name' : IDL.Text,
    'team' : IDL.Text,
    'price' : IDL.Nat,
    'position' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const Contest = IDL.Record({
    'id' : IDL.Nat,
    'participants' : IDL.Vec(IDL.Principal),
    'name' : IDL.Text,
    'entryFee' : IDL.Nat,
    'prizePool' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'balance' : IDL.Nat, 'name' : IDL.Text });
  const FantasyTeam = IDL.Record({
    'id' : IDL.Nat,
    'playerIds' : IDL.Vec(IDL.Nat),
    'owner' : IDL.Principal,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addPlayer' : IDL.Func([Player], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'awardPrize' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createContest' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [IDL.Nat], []),
    'createTeam' : IDL.Func([IDL.Vec(IDL.Nat)], [IDL.Nat], []),
    'depositFunds' : IDL.Func([IDL.Nat], [], []),
    'getAllContests' : IDL.Func([], [IDL.Vec(Contest)], ['query']),
    'getAllPlayers' : IDL.Func([], [IDL.Vec(Player)], ['query']),
    'getBalance' : IDL.Func([], [IDL.Nat], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContest' : IDL.Func([IDL.Nat], [IDL.Opt(Contest)], ['query']),
    'getMyTeams' : IDL.Func([], [IDL.Vec(FantasyTeam)], ['query']),
    'getPlayer' : IDL.Func([IDL.Nat], [IDL.Opt(Player)], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getTeam' : IDL.Func([IDL.Nat], [IDL.Opt(FantasyTeam)], ['query']),
    'getUser' : IDL.Func([], [UserProfile], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'joinContest' : IDL.Func([IDL.Nat], [], []),
    'registerUser' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updatePlayer' : IDL.Func([IDL.Nat, Player], [], []),
  });
};

export const init = ({ IDL }) => { return []; };